addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.8")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.1.1")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.1.18")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.22")
addSbtPlugin("org.tpolecat"       % "tut-plugin"      % "0.6.4")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "2.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.2.27")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.6.0-M3")
